version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./test.db}
      - SECRET_KEY=${SECRET_KEY:-supersecret}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: zapchat
      POSTGRES_PASSWORD: zapchat
      POSTGRES_DB: zapchat
    ports:
      - "5432:5432"
